
def get_api_key():
    return "eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiIzZmMxYzc4My1iY2MyLTRjZTAtOTM3ZC1jYWY4OTQwYjFjODMifQ=="
